import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

const OutfitFont = Outfit({
   variable: "--font-outfit",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
   return (
      <html lang="pt-BR" className={`${OutfitFont.variable} h-full antialiased`}>
         <body className="min-h-full flex flex-col">{children}</body>
      </html>
   );
}
