import type { Metadata } from "next";
import { Outfit, Sora } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const OutfitFont = Outfit({
   variable: "--font-outfit",
   subsets: ["latin"],
});

const SoraFont = Sora({
   variable: "--font-sora",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Quem Sabe Mais?",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
   return (
      <html lang="pt-BR" className={`${OutfitFont.variable} ${SoraFont.variable} h-full antialiased`}>
         <body className="min-h-full flex flex-col">
            <Header />
            <main>{children}</main>
         </body>
      </html>
   );
}
